name: Run ESLint and Prettier

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, prettier:run, and lint
        run: |
          npm install
          npm run prettier:run
          npm run lint
        working-directory: frontend